; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps = 
    ncmreynolds/ld2410 @ ^0.2.2
    crankyoldgit/IRremoteESP8266 @ ^2.8.6
    sui77/rc-switch @ ^2.6.4

; -------------------------------------------------------------
; Choose WHICH test to compile by uncommenting ONE of the lines below:
; -------------------------------------------------------------
build_src_filter = +<main.cpp>
; build_src_filter = +<mmwave_test.cpp>
; build_src_filter = +<ir_sender_test.cpp>
; build_src_filter = +<relay_test.cpp>
; build_src_filter = +<rf_test.cpp>
; build_src_filter = +<working_ir_receiver.cpp>
